[package]

name = "js"
version = "0.0.1"
authors = ["Matt <dev@mttyng.com>"]

[lib]

name = "js"
path = "src/lib/lib.rs"

[[bin]]

name = "js"
path = "src/bin/bin.rs"

[dependencies]
url = "1.7.0"
rand = "0.3.1"
time = "0.1"
log = "0.3.6"
percent-encoding = "1.0.1"
llvm-rs = { path ="../llvm-rs"}
